/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZyphoriaRouteImport } from './routes/zyphoria'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ApiSyncToSheetsRouteImport } from './routes/api.sync-to-sheets'

const ZyphoriaRoute = ZyphoriaRouteImport.update({
  id: '/zyphoria',
  path: '/zyphoria',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncToSheetsRoute = ApiSyncToSheetsRouteImport.update({
  id: '/api/sync-to-sheets',
  path: '/api/sync-to-sheets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/zyphoria': typeof ZyphoriaRoute
  '/api/sync-to-sheets': typeof ApiSyncToSheetsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/zyphoria': typeof ZyphoriaRoute
  '/api/sync-to-sheets': typeof ApiSyncToSheetsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/zyphoria': typeof ZyphoriaRoute
  '/api/sync-to-sheets': typeof ApiSyncToSheetsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/zyphoria'
    | '/api/sync-to-sheets'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/zyphoria'
    | '/api/sync-to-sheets'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/zyphoria'
    | '/api/sync-to-sheets'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  ZyphoriaRoute: typeof ZyphoriaRoute
  ApiSyncToSheetsRoute: typeof ApiSyncToSheetsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zyphoria': {
      id: '/zyphoria'
      path: '/zyphoria'
      fullPath: '/zyphoria'
      preLoaderRoute: typeof ZyphoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-to-sheets': {
      id: '/api/sync-to-sheets'
      path: '/api/sync-to-sheets'
      fullPath: '/api/sync-to-sheets'
      preLoaderRoute: typeof ApiSyncToSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  ZyphoriaRoute: ZyphoriaRoute,
  ApiSyncToSheetsRoute: ApiSyncToSheetsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
